'use client'

// useActionState — a refusal (a missing criterion, a body too long) re-renders
// in place without losing what was typed; success navigates server-side.
import { useActionState } from 'react'

import { saveVenueReview, type VenueFormState } from '@/app/(app)/lieux/actions'
import { Button } from '@/components/ui/button'
import { FieldError, Label, Select, Textarea } from '@/components/ui/field'
import { m } from '@/lib/i18n'
import {
  VENUE_REVIEW_CRITERIA,
  VENUE_REVIEW_LIMITS,
  type VenueReviewCriterion,
} from '@/lib/venues/model'

const copy = m.venues.reviews

const CRITERION_VALUES = [1, 2, 3, 4, 5] as const

/**
 * The review form — three named criteria and a word, nothing else, because
 * there is nothing else to write (ADR 0011, D4): the mean is generated by the
 * database and no field for it exists anywhere.
 *
 * Keyed by the caller on the saved values (app/CLAUDE.md): React 19 resets a
 * form to its mount-time defaults after the action returns, and selects whose
 * values come from the server must be remounted on them.
 */
export function VenueReviewForm({
  venueId,
  slug,
  existing,
}: {
  venueId: string
  slug: string
  existing: { welcome: number; comfort: number; advice: number; body: string | null } | null
}) {
  const [state, formAction] = useActionState<VenueFormState, FormData>(saveVenueReview, {})

  return (
    <form action={formAction} className="flex flex-col gap-4">
      <input type="hidden" name="venueId" value={venueId} />
      <input type="hidden" name="slug" value={slug} />

      <fieldset className="flex flex-col gap-3">
        <legend className="font-display text-xl">
          {existing ? copy.formLegendEdit : copy.formLegendNew}
        </legend>
        <p className="text-ink-muted measure text-xs leading-relaxed">{copy.guard}</p>

        <div className="flex flex-wrap gap-4">
          {VENUE_REVIEW_CRITERIA.map((criterion: VenueReviewCriterion) => (
            <div key={criterion} className="flex flex-col gap-1">
              <Label htmlFor={`avis-${criterion}`}>{copy.criteria[criterion]}</Label>
              <Select
                id={`avis-${criterion}`}
                name={criterion}
                defaultValue={existing ? String(existing[criterion]) : ''}
                required
              >
                <option value="" disabled>
                  —
                </option>
                {CRITERION_VALUES.map((value) => (
                  <option key={value} value={value}>
                    {value}
                    {copy.onFive}
                  </option>
                ))}
              </Select>
            </div>
          ))}
        </div>

        <div className="flex flex-col gap-1">
          <Label htmlFor="avis-body">{copy.bodyLabel}</Label>
          <Textarea
            id="avis-body"
            name="body"
            rows={3}
            maxLength={VENUE_REVIEW_LIMITS.bodyMax}
            defaultValue={existing?.body ?? ''}
            placeholder={copy.bodyPlaceholder}
          />
        </div>
      </fieldset>

      {state.error ? <FieldError>{state.error}</FieldError> : null}

      <div>
        <Button type="submit">{existing ? copy.submitEdit : copy.submitNew}</Button>
      </div>
    </form>
  )
}
